#!/usr/bin/env bash
# Install NAS backup + deploy tooling on 192.168.1.11 (Ubuntu).
# Run as root from this directory: sudo bash install.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NAS_IP="${NAS_IP:-192.168.1.136}"
NAS_SHARE="${NAS_SHARE:-Backups}"
NAS_MOUNT="${NAS_MOUNT:-/mnt/nas/backups}"
NAS_USER="${NAS_USER:-Databytes}"
CRED_FILE="/etc/nas-backup.credentials"
CONF_FILE="/etc/app-backup.conf"
HOST_ID="${BACKUP_HOST_ID:-192.168.1.11}"

log() { printf '[%s] %s\n' "$(date -Iseconds)" "$*"; }
die() { log "ERROR: $*"; exit 1; }
[[ "$(id -u)" -eq 0 ]] || die "run as root (sudo bash install.sh)"

export DEBIAN_FRONTEND=noninteractive
log "Installing packages (cifs-utils rsync sqlite3)"
apt-get update -qq
apt-get install -y -qq cifs-utils rsync sqlite3 curl >/dev/null

log "Installing scripts to /usr/local/bin"
install -m 0755 "$SCRIPT_DIR/backup-apps.sh" /usr/local/bin/backup-apps.sh
install -m 0755 "$SCRIPT_DIR/deploy-app.sh" /usr/local/bin/deploy-app.sh
install -m 0755 "$SCRIPT_DIR/inventory-apps.sh" /usr/local/bin/inventory-apps.sh
install -m 0755 "$SCRIPT_DIR/restore-drill.sh" /usr/local/bin/restore-drill.sh

mkdir -p "$NAS_MOUNT" /var/log
mkdir -p "$NAS_MOUNT" 2>/dev/null || true

if [[ ! -f "$CRED_FILE" ]]; then
  if [[ -n "${NAS_PASSWORD:-}" ]]; then
    umask 077
    cat > "$CRED_FILE" <<EOF
username=$NAS_USER
password=$NAS_PASSWORD
EOF
    chmod 600 "$CRED_FILE"
    log "Wrote $CRED_FILE from NAS_PASSWORD env"
  elif [[ -f "$SCRIPT_DIR/nas-credentials" ]]; then
    install -m 0600 "$SCRIPT_DIR/nas-credentials" "$CRED_FILE"
    log "Installed credentials from ./nas-credentials"
  else
    die "Missing NAS credentials. Set NAS_PASSWORD env or create $SCRIPT_DIR/nas-credentials (username=/password=)"
  fi
else
  log "Using existing $CRED_FILE"
fi

FSTAB_LINE="//${NAS_IP}/${NAS_SHARE}  ${NAS_MOUNT}  cifs  credentials=${CRED_FILE},uid=0,gid=0,file_mode=0640,dir_mode=0750,iocharset=utf8,_netdev,x-systemd.automount  0  0"
if grep -qF "$NAS_MOUNT" /etc/fstab; then
  log "fstab already references $NAS_MOUNT (leaving as-is)"
else
  echo "$FSTAB_LINE" >> /etc/fstab
  log "Added fstab entry for //${NAS_IP}/${NAS_SHARE}"
fi

log "Mounting NAS"
mount "$NAS_MOUNT" 2>/dev/null || mount -a || true
mountpoint -q "$NAS_MOUNT" || {
  # try alternate common Synology share names
  for share in backups Backup backup data Data homes; do
    [[ "$share" == "$NAS_SHARE" ]] && continue
    log "Trying share //$NAS_IP/$share"
    sed -i "s|//${NAS_IP}/${NAS_SHARE}|//${NAS_IP}/${share}|" /etc/fstab || true
    NAS_SHARE="$share"
    mount "$NAS_MOUNT" && break || true
  done
}
mountpoint -q "$NAS_MOUNT" || die "Could not mount NAS at $NAS_MOUNT. Check share name (NAS_SHARE) and credentials."

mkdir -p "$NAS_MOUNT/$HOST_ID/nightly" "$NAS_MOUNT/$HOST_ID/deploy"
TEST_FILE="$NAS_MOUNT/$HOST_ID/.write-test-$$"
echo ok > "$TEST_FILE"
rm -f "$TEST_FILE"
log "NAS write OK: $NAS_MOUNT/$HOST_ID"

log "Running inventory"
/usr/local/bin/inventory-apps.sh | tee /var/log/app-backup-inventory.txt

if [[ -f "$SCRIPT_DIR/app-backup.conf" ]]; then
  install -m 0644 "$SCRIPT_DIR/app-backup.conf" "$CONF_FILE"
  log "Installed $CONF_FILE from package"
elif [[ ! -f "$CONF_FILE" ]]; then
  # extract draft lines from inventory output
  awk '/^# name\|/{flag=1} flag && /^[^#].*\|/{print} /^=== /{if(flag&&NR>1)flag=0}' /var/log/app-backup-inventory.txt > "$CONF_FILE.tmp" || true
  if [[ -s "$CONF_FILE.tmp" ]]; then
    {
      echo "# Auto-generated by install.sh — review paths"
      echo "# name|app_root|sqlite_paths_csv|upload_paths_csv|pm2_name"
      cat "$CONF_FILE.tmp"
    } > "$CONF_FILE"
    log "Wrote draft $CONF_FILE from inventory"
  else
    install -m 0644 "$SCRIPT_DIR/app-backup.conf.example" "$CONF_FILE"
    log "Installed example $CONF_FILE — EDIT paths before relying on backups"
  fi
  rm -f "$CONF_FILE.tmp"
else
  log "Keeping existing $CONF_FILE"
fi

CRON_LINE='15 2 * * * /usr/local/bin/backup-apps.sh nightly >> /var/log/app-backup.log 2>&1'
( crontab -l 2>/dev/null | grep -v 'backup-apps.sh nightly' ; echo "$CRON_LINE" ) | crontab -
log "Installed root cron: $CRON_LINE"

log "Running first nightly backup"
/usr/local/bin/backup-apps.sh nightly | tee -a /var/log/app-backup.log

log "Running non-destructive restore drill"
/usr/local/bin/restore-drill.sh --auto || log "WARN: restore drill reported issues (see output)"

log "Install complete."
log "Deploy with: deploy-app.sh <app-name>"
log "Manual backup: backup-apps.sh nightly|deploy [app-name]"
